### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#1]
I am currently unable to build SELint on Debian sid.

With either the v1.0.0 tarball or the git master branch I am getting the following errors:

```
$ ./autogen.sh
$ ./configure
..
./configure: line 5538: syntax error near unexpected token `drd,'
./configure: line 5538: `AX_VALGRIND_DFLT(drd, off)
```

All the listed dependencies are installed, also valgrind version 3.15.0.

**Comment by dburgener** [comment]
Sorry about that!

Looks like I had a bad assumption about the tarball.  I thought github automatically ran "make dist" on an autotools project for some reason.  I've uploaded a "make dist" output tarball, which should behave as expected for the tarball instructions and not run into the issue you're encountering

On the build from source end of things, did you install autoconf-archive?  I reproduced your issue on debian sid without autoconf-archive, and then I had to rerun autogen.sh after installing it in order to get ./configure working correctly.

Let me know if one or both of those approaches gets you building.

**Comment by cgzones** [comment]
Thanks, I was missing `autoconf-archive` indeed.

**Comment by freedom1b2830** [comment]
arch linux now

**Comment by dburgener** [comment]
Can you please provide more details?  The original report involved the git master branch and the 1.0.0 tarball.  I assume you're not using 1.0.0 at this point.  Is this a build from source failure, or a build from tarball failure?  Did you rerun autogen.sh after installing autoconf-archive as suggested above?

**Comment by freedom1b2830** [comment]
commit 6becdd9f523f857dc23b97bc5097c6ceecd81817

Last time I tried to re-execute ./autogen.sh
There was no effect.
Apparently multiple updates in the system affected.

``Its OK now.``
