### ISSUE TITLE
another build dependency

### ISSUE THREAD

**Issue by dac4755** [TresysTechnology/selint#17]
The README says, "you'll also need the autoconf-archive package" for building from the repo. On F31 I also needed to install "automake" or you get:

$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

**Comment by dac4755** [comment]
some more that configure reports but doesn't fail for, like 
checking for flex... no
checking for lex... no
checking for bison... no
checking for byacc... no
then it seems to build without problems.

**Comment by dburgener** [comment]
First issue is fixed in 843e0e6726db5e9daaf92c879335405d772ff425.  On the second, is that in the release tarball or building from source in the repo?  In the release, autotools packages up yacc and flex into a program called "ylwrap" in order to remove those dependencies, but I'm not sure why it would be working without that if none of those are present.

**Comment by dburgener** [comment]
It seems like the second item isn't a real issue anyways, so I'm going to go ahead and close this issue.
