### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by cgzones** [TresysTechnology/selint#177]
The freeze window of the new Debian release is approaching (early next year) and I'd like to have the accumulated changes in the next Debian stable distribution.

Any chance for releasing a new version somewhen in December?
Are there any relevant features missing or yet unfit for a release?

**Comment by dburgener** [comment]
That sounds good.  I don't think there's a reason to not make that happen.  A few things I'd ideally like to get in (although I don't think any are strictly speaking blocking:

* PR #175 
* I've been speaking with a developer at Tresys offline about a check he'd like that he's been working on implementing.  He's interested in a error check for duplicate file context definitions and is in process on making one.  I can't find a github account for him otherwise I'd mention him here.
* I just submitted #178 which I noticed a while back and haven't had time to look into yet

I should definitely be able to find time to finish #175 in the next week or so to support a release early next week.  I'll try to find time to look at #178 as well, but I'm not sure whether I'll have time.

As long as I get #175 in, I'm okay with a release early next week regardless of the status of the other two.  Although #178 is technically a regression, so I have a preference towards addressing it rather than potentially break someone on 1.1 to 1.2 upgrade.

**Comment by dburgener** [comment]
Meant to ping @stevedlawrence in case he has any comments on this as well.

**Comment by stevedlawrence** [comment]
Fine with me.

Pinging @gdesrosi for the duplicate filecontext change. Agreed that would be nice to get in if possible, but I wouldn't consider a blocker, though I think it's close to being complete.

**Comment by dburgener** [comment]
Release 1.2.0 made.  Thanks everyone for your contributions to this release!
